version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      android-build-tooling-patches:
        patterns:
          - "com.android.application"
          - "com.android.kotlin.multiplatform.library"
        update-types:
          - "patch"
      compose-patches:
        patterns:
          - "androidx.compose:*"
        update-types:
          - "patch"
      lifecycle-patches:
        patterns:
          - "androidx.lifecycle:*"
        update-types:
          - "patch"
